/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Main.Login;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jason01
 */
public class AdminTopUp extends javax.swing.JFrame {
    private AdminFunctions adminFunctions;
    private String username1;
    /**
     * Creates new form AdminTopUp
     */
    public AdminTopUp(String username1) {
        this(new AdminFunctions(), username1);
    }

    public AdminTopUp(AdminFunctions adminFunctions, String username1) {
        this.adminFunctions = adminFunctions;
        this.username1 = username1;
        initComponents();
        adminFunctions.LoadAccountTable(accountTable);
        setTitle("Manage Account");
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        topupclearbutton = new javax.swing.JButton();
        topupdeductbutton = new javax.swing.JButton();
        topupaddbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        useridField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        balanceField = new javax.swing.JTextField();
        valueField = new javax.swing.JTextField();
        accountidField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setText("MANAGE USER");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "AccountID", "UserID", "Username", "Balance"
            }
        ));
        accountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accountTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(accountTable);

        jLabel1.setText("Search");

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel5.setText("TOP UP");

        topupclearbutton.setText("CLEAR");
        topupclearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topupclearbuttonActionPerformed(evt);
            }
        });

        topupdeductbutton.setText("DEDUCT");
        topupdeductbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topupdeductbuttonActionPerformed(evt);
            }
        });

        topupaddbutton.setText("ADD");
        topupaddbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topupaddbuttonActionPerformed(evt);
            }
        });

        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        jLabel3.setText("UserID");

        jLabel6.setText("Username");

        jLabel7.setText("Balance");

        jLabel8.setText("Value");

        useridField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                useridFieldMouseReleased(evt);
            }
        });

        usernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                usernameFieldMouseReleased(evt);
            }
        });

        balanceField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                balanceFieldMouseReleased(evt);
            }
        });

        valueField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                valueFieldMouseReleased(evt);
            }
        });
        valueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueFieldActionPerformed(evt);
            }
        });

        accountidField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accountidFieldMouseReleased(evt);
            }
        });

        jLabel9.setText("AccountID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(topupdeductbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(useridField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(usernameField)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(valueField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(balanceField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(backbutton)
                                            .addComponent(topupaddbutton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(topupclearbutton))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(accountidField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accountidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(useridField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(valueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(topupclearbutton)
                            .addComponent(topupdeductbutton)
                            .addComponent(topupaddbutton))
                        .addGap(33, 33, 33)
                        .addComponent(backbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void topupdeductbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topupdeductbuttonActionPerformed
        // TODO add your handling code here:
        adminFunctions.AccountTableDeductBalance(username1, this, accountTable,(DefaultTableModel) accountTable.getModel(), accountTable.getSelectedRow(), accountidField, useridField, usernameField, balanceField, valueField, searchField);
    }//GEN-LAST:event_topupdeductbuttonActionPerformed

    private void topupclearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topupclearbuttonActionPerformed
        // TODO add your handling code here:
        adminFunctions.TopUpPageClearData(accountTable, accountidField, useridField, usernameField, balanceField, valueField, searchField);
    }//GEN-LAST:event_topupclearbuttonActionPerformed

    private void accountTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountTableMouseReleased
        // TODO add your handling code here:
        adminFunctions.AccountTableMouseReleased(accountTable, accountidField, useridField, usernameField, balanceField, valueField);
    }//GEN-LAST:event_accountTableMouseReleased

    private void topupaddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topupaddbuttonActionPerformed
        // TODO add your handling code here:
        adminFunctions.AccountTableAddBalance(username1, this, accountTable,(DefaultTableModel) accountTable.getModel(), accountTable.getSelectedRow(), accountidField, useridField, usernameField, balanceField, valueField, searchField);
    }//GEN-LAST:event_topupaddbuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        adminFunctions.MainPage(this, username1);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void accountidFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountidFieldMouseReleased
        // TODO add your handling code here:
        adminFunctions.TopUpPageShowErrorDialog(accountidField, "Account ID", accountTable);
    }//GEN-LAST:event_accountidFieldMouseReleased

    private void useridFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useridFieldMouseReleased
        // TODO add your handling code here:
        adminFunctions.TopUpPageShowErrorDialog(useridField, "User ID", accountTable);
    }//GEN-LAST:event_useridFieldMouseReleased

    private void usernameFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFieldMouseReleased
        // TODO add your handling code here:
        adminFunctions.TopUpPageShowErrorDialog(usernameField, "Username", accountTable);
    }//GEN-LAST:event_usernameFieldMouseReleased

    private void balanceFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceFieldMouseReleased
        // TODO add your handling code here:
        adminFunctions.TopUpPageShowErrorDialog(balanceField, "Balance", accountTable);
    }//GEN-LAST:event_balanceFieldMouseReleased

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        adminFunctions.AccountTableSearchField(accountTable, searchField);
    }//GEN-LAST:event_searchFieldKeyReleased

    private void valueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueFieldActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_valueFieldActionPerformed

    private void valueFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valueFieldMouseReleased
        // TODO add your handling code here:\
        if (accountTable.getSelectedRow() == -1) {
           adminFunctions.TopUpPageShowErrorDialog(valueField, "Value", accountTable); 
           adminFunctions.TopUpPageClearData(accountTable, accountidField, useridField, usernameField, balanceField, valueField, searchField);
        }
    }//GEN-LAST:event_valueFieldMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {     
        java.awt.EventQueue.invokeLater(() -> {  
            new Login().setVisible(true);  // Start with the login page  
        });  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountTable;
    private javax.swing.JTextField accountidField;
    private javax.swing.JButton backbutton;
    private javax.swing.JTextField balanceField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton topupaddbutton;
    private javax.swing.JButton topupclearbutton;
    private javax.swing.JButton topupdeductbutton;
    private javax.swing.JTextField useridField;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField valueField;
    // End of variables declaration//GEN-END:variables
}
