/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testing;

/**
 *
 * @author User
 */
public class DeliveryRunner_MainPage extends javax.swing.JFrame {
    private DeliveryRunnerFunctions functions = new DeliveryRunnerFunctions();
    
    /**
     * Creates new form DeliveryRunner_MainPage
     */
        public DeliveryRunner_MainPage() {
        this(new DeliveryRunnerFunctions());
    }
    
    public DeliveryRunner_MainPage(DeliveryRunnerFunctions functions) {
        this.functions = functions;
        initComponents();
//      DeliveryRunner_LoginPage login = new DeliveryRunner_LoginPage();
//      usernamelabel.setText(login.getUsername());
        setTitle("Delivery Runner Main Page");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        tasksbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        tasksstatusbutton = new javax.swing.JButton();
        revenuedashboardbutton = new javax.swing.JButton();
        taskshistorybutton = new javax.swing.JButton();
        readcustomerreviewbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("HELLO , WELCOME !");

        usernamelabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        usernamelabel.setText("jLabel3");

        tasksbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tasksbutton.setText("VIEW TASKS");
        tasksbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksbuttonActionPerformed(evt);
            }
        });

        logoutbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutbutton.setText("LOGOUT");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        tasksstatusbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tasksstatusbutton.setText("UPDATE TASKS STATUS");
        tasksstatusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksstatusbuttonActionPerformed(evt);
            }
        });

        revenuedashboardbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        revenuedashboardbutton.setText("REVENUE DASHBOARD");
        revenuedashboardbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenuedashboardbuttonActionPerformed(evt);
            }
        });

        taskshistorybutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        taskshistorybutton.setText("CHECK TASKS HISTORY");
        taskshistorybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskshistorybuttonActionPerformed(evt);
            }
        });

        readcustomerreviewbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        readcustomerreviewbutton.setText("READ CUSTOMER REVIEW");
        readcustomerreviewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readcustomerreviewbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(usernamelabel)
                .addGap(183, 183, 183)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tasksbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasksstatusbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(revenuedashboardbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taskshistorybutton, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(readcustomerreviewbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(277, 277, 277))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernamelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(tasksbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tasksstatusbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readcustomerreviewbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taskshistorybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(revenuedashboardbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tasksbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksbuttonActionPerformed
        // TODO add your handling code here:
        functions.ViewTasks(this);
    }//GEN-LAST:event_tasksbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        // Display a confirmation dialog
        functions.LogOut(this);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void taskshistorybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskshistorybuttonActionPerformed
        // TODO add your handling code here:
        functions.TasksHistory(this);
    }//GEN-LAST:event_taskshistorybuttonActionPerformed

    private void revenuedashboardbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenuedashboardbuttonActionPerformed
        // TODO add your handling code here:
        functions.RevenueDashboard(this);
    }//GEN-LAST:event_revenuedashboardbuttonActionPerformed

    private void tasksstatusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksstatusbuttonActionPerformed
        // TODO add your handling code here:
        functions.TaskStatus(this);
    }//GEN-LAST:event_tasksstatusbuttonActionPerformed

    private void readcustomerreviewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readcustomerreviewbuttonActionPerformed
        // TODO add your handling code here:
        functions.ReadCustomerReview(this);
    }//GEN-LAST:event_readcustomerreviewbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        DeliveryRunnerFunctions functions = new DeliveryRunnerFunctions();

        java.awt.EventQueue.invokeLater(() -> {
            new DeliveryRunner_MainPage(functions).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton readcustomerreviewbutton;
    private javax.swing.JButton revenuedashboardbutton;
    private javax.swing.JButton tasksbutton;
    private javax.swing.JButton taskshistorybutton;
    private javax.swing.JButton tasksstatusbutton;
    private javax.swing.JLabel usernamelabel;
    // End of variables declaration//GEN-END:variables
}
