/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testing;

import org.json.JSONObject;
import org.json.JSONException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LEE YONG JUN
 */
public class DeliveryRunner_ViewTasks extends javax.swing.JFrame {
    private DeliveryRunnerFunctions functions;

    /**
     * Creates new form DeliveryRunner_ViewTask
     */
     public DeliveryRunner_ViewTasks() {
        this(new DeliveryRunnerFunctions());
    }
    
    public DeliveryRunner_ViewTasks(DeliveryRunnerFunctions functions) {
        this.functions = functions;
        initComponents();
        setTitle("Delivery Runner View Tasks Page");
        setLocationRelativeTo(null);
        
        DefaultTableModel model = (DefaultTableModel) taskstable.getModel();
        DeliveryRunnerFunctions runnerFunctions = new DeliveryRunnerFunctions();
        runnerFunctions.loadDeliveryTasksTable(model);
    }
    public String formatTaskDetails(String deliveryID, String orderID, String runnerID, String houseNumber, String streetName, String residentialArea, String postalCode, String city, String state) {
        return "Delivery ID: " + deliveryID + "\n" +
               "Order ID: " + orderID + "\n" +
               "Delivery Runner ID: " + runnerID + "\n" +
               "Delivery Address: " + houseNumber + ", " + streetName + ", " + residentialArea + ", " + postalCode + ", " + city + ", " + state;
    }
    public void clearTextFields() {
        deliveryidtxtfield.setText("");
        orderidtxtfield.setText("");
        deliveryrunneridtxtfield.setText("");
        housenumbertxtfield.setText("");
        streetnametxtfield.setText("");
        residentialareatxtfield.setText("");
        postalcodetxtfield.setText("");
        citytxtfield.setText("");
        statetxtfield.setText("");
        searchtxtfield.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        orderidtxtfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deliveryrunneridtxtfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        housenumbertxtfield = new javax.swing.JTextField();
        acceptbutton = new javax.swing.JButton();
        declinebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        deliveryidtxtfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        searchtxtfield = new javax.swing.JTextField();
        statusbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taskstable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        streetnametxtfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        residentialareatxtfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        postalcodetxtfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        citytxtfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        statetxtfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel1.setText("VIEW TASKS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ORDER ID : ");

        orderidtxtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                orderidtxtfieldMouseReleased(evt);
            }
        });
        orderidtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderidtxtfieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("DELIVERY RUNNER ID : ");

        deliveryrunneridtxtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deliveryrunneridtxtfieldMouseReleased(evt);
            }
        });
        deliveryrunneridtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryrunneridtxtfieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("HOUSE NUMBER : ");

        housenumbertxtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                housenumbertxtfieldMouseReleased(evt);
            }
        });
        housenumbertxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housenumbertxtfieldActionPerformed(evt);
            }
        });

        acceptbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        acceptbutton.setText("ACCEPT TASK");
        acceptbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptbuttonActionPerformed(evt);
            }
        });

        declinebutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        declinebutton.setText("DECLINE TASK");
        declinebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declinebuttonActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbutton.setText("CLEAR");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        backbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("DELIVERY ID : ");

        deliveryidtxtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryidtxtfieldMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deliveryidtxtfieldMouseReleased(evt);
            }
        });
        deliveryidtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryidtxtfieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("SEARCH : ");

        searchtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtfieldActionPerformed(evt);
            }
        });
        searchtxtfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtfieldKeyReleased(evt);
            }
        });

        statusbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusbutton.setText("STATUS");
        statusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusbuttonActionPerformed(evt);
            }
        });

        taskstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Delivery ID", "Order ID", "Delivery Runner ID", "House Number", "Street Name", "Residential Area", "Postal Code", "City", "State"
            }
        ));
        taskstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                taskstableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(taskstable);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("STREET NAME : ");

        streetnametxtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                streetnametxtfieldMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("RESIDENTIAL AREA : ");

        residentialareatxtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                residentialareatxtfieldMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("POSTAL CODE : ");

        postalcodetxtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                postalcodetxtfieldMouseReleased(evt);
            }
        });
        postalcodetxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalcodetxtfieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("CITY : ");

        citytxtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                citytxtfieldMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("STATE : ");

        statetxtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                statetxtfieldMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(clearbutton)
                        .addGap(18, 18, 18)
                        .addComponent(statusbutton)
                        .addGap(18, 18, 18)
                        .addComponent(backbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel13))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(citytxtfield, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(statetxtfield)
                                    .addComponent(postalcodetxtfield)
                                    .addComponent(residentialareatxtfield)
                                    .addComponent(streetnametxtfield)
                                    .addComponent(housenumbertxtfield)
                                    .addComponent(deliveryrunneridtxtfield)
                                    .addComponent(deliveryidtxtfield)
                                    .addComponent(orderidtxtfield)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(acceptbutton)
                        .addGap(51, 51, 51)
                        .addComponent(declinebutton)
                        .addGap(65, 65, 65)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchtxtfield))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(deliveryidtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(orderidtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(deliveryrunneridtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(housenumbertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(streetnametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(residentialareatxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(postalcodetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(citytxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(statetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(acceptbutton)
                                    .addComponent(declinebutton))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(statusbutton)
                                    .addComponent(backbutton)
                                    .addComponent(clearbutton)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        functions.MainPage(this);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        functions.TasksPageClearData(
            taskstable, 
            deliveryidtxtfield, 
            orderidtxtfield, 
            deliveryrunneridtxtfield, 
            housenumbertxtfield, 
            streetnametxtfield, 
            residentialareatxtfield, 
            postalcodetxtfield, 
            citytxtfield, 
            statetxtfield, 
            searchtxtfield
        );
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void acceptbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptbuttonActionPerformed
        // TODO add your handling code here:
        int row = taskstable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a task to accept!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Retrieve the task details from the selected row
        String deliveryID = taskstable.getValueAt(row, 0).toString();
        String orderID = taskstable.getValueAt(row, 1).toString();
        String runnerID = taskstable.getValueAt(row, 2).toString();
        String houseNumber = taskstable.getValueAt(row, 3).toString();
        String streetName = taskstable.getValueAt(row, 4).toString();
        String residentialArea = taskstable.getValueAt(row, 5).toString();
        String postalCode = taskstable.getValueAt(row, 6).toString();
        String city = taskstable.getValueAt(row, 7).toString();
        String state = taskstable.getValueAt(row, 8).toString();

        // Format the task details into a readable string
        String taskDetails = formatTaskDetails(deliveryID, orderID, runnerID, houseNumber, streetName, residentialArea, postalCode, city, state);

        // Display the confirmation message with task details
        int accept = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to accept the following task?\n\n" + taskDetails, 
            "Confirm Accept?", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);

        if (accept == JOptionPane.YES_OPTION) {
            // Update the order status to "Accepted" in orders.txt
            boolean success = functions.updateOrderStatus(orderID, "Accepted");

            if (success) {
                // Notify the customer
                String customerID = functions.getCustomerIDFromOrder(orderID); // Get the customer ID from the order
                String notificationContent = "Your order " + orderID + " has been accepted";
                functions.sendNotification(customerID, notificationContent);

                JOptionPane.showMessageDialog(this, "Task accepted successfully!", "Task Accepted", JOptionPane.INFORMATION_MESSAGE);

                // Clear the text fields
                clearTextFields();

                // Refresh the table to reflect the changes
                DefaultTableModel model = (DefaultTableModel) taskstable.getModel();
                functions.loadDeliveryTasksTable(model);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to accept the task. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_acceptbuttonActionPerformed

    private void orderidtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderidtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderidtxtfieldActionPerformed

    private void deliveryrunneridtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryrunneridtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryrunneridtxtfieldActionPerformed

    private void housenumbertxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housenumbertxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_housenumbertxtfieldActionPerformed

    private void searchtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxtfieldActionPerformed

    private void searchtxtfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtfieldKeyReleased
        // TODO add your handling code here:
        functions.TasksTableSearchField(taskstable, searchtxtfield);
    }//GEN-LAST:event_searchtxtfieldKeyReleased

    private void declinebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declinebuttonActionPerformed
        // TODO add your handling code here:
        int row = taskstable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a task to decline!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Retrieve the task details from the selected row
        String deliveryID = taskstable.getValueAt(row, 0).toString();
        String orderID = taskstable.getValueAt(row, 1).toString();
        String runnerID = taskstable.getValueAt(row, 2).toString();
        String houseNumber = taskstable.getValueAt(row, 3).toString();
        String streetName = taskstable.getValueAt(row, 4).toString();
        String residentialArea = taskstable.getValueAt(row, 5).toString();
        String postalCode = taskstable.getValueAt(row, 6).toString();
        String city = taskstable.getValueAt(row, 7).toString();
        String state = taskstable.getValueAt(row, 8).toString();

        // Format the task details into a readable string
        String taskDetails = functions.formatTaskDetails(deliveryID, orderID, runnerID, houseNumber, streetName, residentialArea, postalCode, city, state);

        // Show the confirmation dialog with task details
        int confirm = JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to decline the following task?\n\n" + taskDetails, 
            "Confirm Decline", 
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            // Step 1: Decline the task (update order status to "Declined")
            boolean declineSuccess = functions.updateOrderStatus(orderID, "Declined");

            if (declineSuccess) {
                // Step 2: Find the next available runner
                String nextRunnerID = functions.findNextAvailableRunner();

                if (nextRunnerID != null) {
                    // Step 3: Reassign the task to the next available runner
                    boolean reassignSuccess = functions.reassignTask(orderID, nextRunnerID);

                    if (reassignSuccess) {
                        // Notify the new runner
                        String notificationContent = "You have been assigned a new task for order " + orderID;
                        functions.sendNotification(nextRunnerID, notificationContent);

                        // Notify the customer
                        String customerID = functions.getCustomerIDFromOrder(orderID);
                        String customerNotification = "Your order " + orderID + " has been reassigned to another runner.";
                        functions.sendNotification(customerID, customerNotification);

                        JOptionPane.showMessageDialog(
                            this, 
                            "Task declined and reassigned to the next available runner.", 
                            "Task Declined", 
                            JOptionPane.INFORMATION_MESSAGE
                        );
                    } else {
                        JOptionPane.showMessageDialog(
                            this, 
                            "Failed to reassign the task. Please try again.", 
                            "Error", 
                            JOptionPane.ERROR_MESSAGE
                        );
                    }
                } else {
                    // Step 4: No available runners
                    String customerID = functions.getCustomerIDFromOrder(orderID);

                    // Notify the customer to choose between dine-in or takeaway
                    String notificationContent = "No delivery runners are available. Please choose between dine-in or takeaway for your order " + orderID + ".";
                    functions.sendNotification(customerID, notificationContent);

                    // Inform the delivery runner that no runners are available
                    JOptionPane.showMessageDialog(
                        this, 
                        "No available runner right now. Customer has been notified to choose between dine-in or takeaway.", 
                        "No Runners Available", 
                        JOptionPane.INFORMATION_MESSAGE
                    );
                }

                // Refresh the table to reflect the changes
                DefaultTableModel model = (DefaultTableModel) taskstable.getModel();
                functions.loadDeliveryTasksTable(model);
            } else {
                JOptionPane.showMessageDialog(
                    this, 
                    "Failed to decline the task. Please try again.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_declinebuttonActionPerformed

    private void taskstableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskstableMouseReleased
        // TODO add your handling code here:
        functions.TasksTableMouseReleased(taskstable, deliveryidtxtfield, orderidtxtfield, deliveryrunneridtxtfield, housenumbertxtfield, streetnametxtfield, residentialareatxtfield, postalcodetxtfield, citytxtfield, statetxtfield);
    }//GEN-LAST:event_taskstableMouseReleased

    private void statusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusbuttonActionPerformed
        // TODO add your handling code here:
        functions.TaskStatus(this);
    }//GEN-LAST:event_statusbuttonActionPerformed

    private void deliveryidtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryidtxtfieldActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_deliveryidtxtfieldActionPerformed

    private void deliveryidtxtfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryidtxtfieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryidtxtfieldMouseClicked

    private void deliveryidtxtfieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryidtxtfieldMouseReleased
        // TODO add your handling code here:
        functions.showAlertIfNoRowSelected(taskstable);
    }//GEN-LAST:event_deliveryidtxtfieldMouseReleased

    private void orderidtxtfieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderidtxtfieldMouseReleased
        // TODO add your handling code here:
        functions.showAlertIfNoRowSelected(taskstable);
    }//GEN-LAST:event_orderidtxtfieldMouseReleased

    private void deliveryrunneridtxtfieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryrunneridtxtfieldMouseReleased
        // TODO add your handling code here:
        functions.showAlertIfNoRowSelected(taskstable);
    }//GEN-LAST:event_deliveryrunneridtxtfieldMouseReleased

    private void housenumbertxtfieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_housenumbertxtfieldMouseReleased
        // TODO add your handling code here:
        functions.showAlertIfNoRowSelected(taskstable);
    }//GEN-LAST:event_housenumbertxtfieldMouseReleased

    private void postalcodetxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalcodetxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postalcodetxtfieldActionPerformed

    private void streetnametxtfieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_streetnametxtfieldMouseReleased
        // TODO add your handling code here:
          functions.showAlertIfNoRowSelected(taskstable);

    }//GEN-LAST:event_streetnametxtfieldMouseReleased

    private void residentialareatxtfieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residentialareatxtfieldMouseReleased
        // TODO add your handling code here:
        functions.showAlertIfNoRowSelected(taskstable);

    }//GEN-LAST:event_residentialareatxtfieldMouseReleased

    private void postalcodetxtfieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postalcodetxtfieldMouseReleased
        // TODO add your handling code here:
          functions.showAlertIfNoRowSelected(taskstable);

    }//GEN-LAST:event_postalcodetxtfieldMouseReleased

    private void citytxtfieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citytxtfieldMouseReleased
        // TODO add your handling code here:
           functions.showAlertIfNoRowSelected(taskstable);

    }//GEN-LAST:event_citytxtfieldMouseReleased

    private void statetxtfieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statetxtfieldMouseReleased
        // TODO add your handling code here:
            functions.showAlertIfNoRowSelected(taskstable);

    }//GEN-LAST:event_statetxtfieldMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        DeliveryRunnerFunctions functions = new DeliveryRunnerFunctions();

        java.awt.EventQueue.invokeLater(() -> {
            new DeliveryRunner_ViewTasks(functions).setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JTextField citytxtfield;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton declinebutton;
    private javax.swing.JTextField deliveryidtxtfield;
    private javax.swing.JTextField deliveryrunneridtxtfield;
    private javax.swing.JTextField housenumbertxtfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField orderidtxtfield;
    private javax.swing.JTextField postalcodetxtfield;
    private javax.swing.JTextField residentialareatxtfield;
    private javax.swing.JTextField searchtxtfield;
    private javax.swing.JTextField statetxtfield;
    private javax.swing.JButton statusbutton;
    private javax.swing.JTextField streetnametxtfield;
    private javax.swing.JTable taskstable;
    // End of variables declaration//GEN-END:variables
}
