/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testing;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;

/**
 *
 * @author LEE YONG JUN
 */
public class DeliveryRunner_CheckTasksHistory extends javax.swing.JFrame {
    private DeliveryRunnerFunctions functions;

    /**
     * Creates new form DeliveryRunner_TasksHistory
     */
    public DeliveryRunner_CheckTasksHistory() {
        this(new DeliveryRunnerFunctions());
    }
    
    public DeliveryRunner_CheckTasksHistory(DeliveryRunnerFunctions functions) {
    this.functions = functions;
    initComponents();
    setTitle("Delivery Runner Check Tasks History");
    setLocationRelativeTo(null);

    // Load all completed/declined tasks
    functions.LoadTasksHistoryTable(taskshistorytable);

        // Load all completed/declined tasks
    //    functions.LoadTasksHistoryTable(taskshistorytable);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskshistorytable = new javax.swing.JTable();
        backbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clearbutton = new javax.swing.JButton();
        searchtxtfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel1.setText("CHECK TASKS HISTORY");

        taskshistorytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer ID", "Vendor ID", "Order Status", "Delivery ID", "House Number", "Street Name", "Residential Area", "Postal Code", "City", "State"
            }
        ));
        taskshistorytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                taskshistorytableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(taskshistorytable);

        backbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("SEARCH : ");

        clearbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbutton.setText("CLEAR");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        searchtxtfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtfieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(backbutton)
                        .addGap(0, 414, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(searchtxtfield)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearbutton)
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearbutton)
                    .addComponent(searchtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(backbutton)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        functions.MainPage(this);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void taskshistorytableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskshistorytableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_taskshistorytableMouseReleased

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        // Unselect any selected row in the table
        taskshistorytable.clearSelection();
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void searchtxtfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtfieldKeyReleased
        // TODO add your handling code here:
        functions.TasksTableSearchField(taskshistorytable, searchtxtfield);
        
    }//GEN-LAST:event_searchtxtfieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        DeliveryRunnerFunctions functions = new DeliveryRunnerFunctions();

        java.awt.EventQueue.invokeLater(() -> {
            new DeliveryRunner_CheckTasksHistory(functions).setVisible(true);
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton clearbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchtxtfield;
    private javax.swing.JTable taskshistorytable;
    // End of variables declaration//GEN-END:variables
}
