/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Main.Login;

/**
 *
 * @author User
 */
public class AdminMainPage extends javax.swing.JFrame {
    private AdminFunctions adminFunctions;
    /**
     * Creates new form DeliveryRunner_MainPage
     */
    public AdminMainPage() {
        this(new AdminFunctions());
    }
    public AdminMainPage(AdminFunctions adminFunctions) { 
        this.adminFunctions = adminFunctions;
        initComponents();
//      LoginPage login = new LoginPage();
//      username = login.getUsername();
//      usernamelabel.setText(username);
        setTitle("Admin Main Page");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        topupcreditButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        generatereceiptButton = new javax.swing.JButton();
        usermanagementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("HELLO , WELCOME !");

        usernamelabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        usernamelabel.setText("jLabel3");

        topupcreditButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        topupcreditButton.setText("TOP UP CREDIT");
        topupcreditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topupcreditButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        logoutButton.setText("LOG OUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        generatereceiptButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        generatereceiptButton.setText("VIEW TRANSACTION");
        generatereceiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatereceiptButtonActionPerformed(evt);
            }
        });

        usermanagementButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        usermanagementButton.setText("USER MANAGEMENT");
        usermanagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermanagementButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(813, 813, 813)
                .addComponent(jLabel2)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generatereceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(topupcreditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usermanagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernamelabel)
                        .addGap(246, 246, 246))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernamelabel))
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usermanagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(topupcreditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(generatereceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        //adminFunctions.LogOut(this, username);
        adminFunctions.LogOut(this);
        Login lg = new Login();
        lg.show();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void topupcreditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topupcreditButtonActionPerformed
        // TODO add your handling code here:
        adminFunctions.TopUpCredit(this);
    }//GEN-LAST:event_topupcreditButtonActionPerformed

    private void generatereceiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatereceiptButtonActionPerformed
        // TODO add your handling code here:
        adminFunctions.GenerateReceipt(this);
    }//GEN-LAST:event_generatereceiptButtonActionPerformed

    private void usermanagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermanagementButtonActionPerformed
        // TODO add your handling code here:
        adminFunctions.UserManagement(this);
    }//GEN-LAST:event_usermanagementButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AdminFunctions adminFunctions = new AdminFunctions();

        java.awt.EventQueue.invokeLater(() -> {
            new AdminMainPage(adminFunctions).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generatereceiptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton topupcreditButton;
    private javax.swing.JButton usermanagementButton;
    private javax.swing.JLabel usernamelabel;
    // End of variables declaration//GEN-END:variables
}
